{{- $fullName := include "madkitty-api.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "madkitty-api.fullname" . }}
  labels:
    {{- include "madkitty-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "madkitty-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "madkitty-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $key, $value := .Values.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $value.targetPort }}
              protocol: {{ $value.protocol }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

