apiVersion: v1
kind: Service
metadata:
  name: {{ include "madkitty-api.fullname" . }}
  labels:
    {{- include "madkitty-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      targetPort: {{ $key }}
      {{- toYaml $value | nindent 6 }}
    {{- end }}
  selector:
    {{- include "madkitty-api.selectorLabels" . | nindent 4 }}
